# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './PyDatalogger01GUI.ui'
#
# Created: Sun Aug 16 15:12:21 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1024, 747)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.line = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMaximumSize(QtCore.QSize(16777215, 3))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 0, 1, 1)
        self.splitter = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMinimumSize(QtCore.QSize(1000, 400))
        self.splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.dataView = PlotWidget(self.splitter)
        self.dataView.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.dataView.sizePolicy().hasHeightForWidth())
        self.dataView.setSizePolicy(sizePolicy)
        self.dataView.setMinimumSize(QtCore.QSize(1000, 400))
        self.dataView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dataView.setObjectName(_fromUtf8("dataView"))
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.tabControl = QtGui.QTabWidget(self.centralwidget)
        self.tabControl.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.tabControl.sizePolicy().hasHeightForWidth())
        self.tabControl.setSizePolicy(sizePolicy)
        self.tabControl.setMinimumSize(QtCore.QSize(1000, 240))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(10)
        self.tabControl.setFont(font)
        self.tabControl.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabControl.setObjectName(_fromUtf8("tabControl"))
        self.tabCmd = QtGui.QWidget()
        self.tabCmd.setObjectName(_fromUtf8("tabCmd"))
        self.label_2 = QtGui.QLabel(self.tabCmd)
        self.label_2.setGeometry(QtCore.QRect(870, 110, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEditCMD = QtGui.QLineEdit(self.tabCmd)
        self.lineEditCMD.setGeometry(QtCore.QRect(870, 130, 121, 22))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditCMD.sizePolicy().hasHeightForWidth())
        self.lineEditCMD.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(10)
        self.lineEditCMD.setFont(font)
        self.lineEditCMD.setObjectName(_fromUtf8("lineEditCMD"))
        self.btnE0 = QtGui.QPushButton(self.tabCmd)
        self.btnE0.setEnabled(True)
        self.btnE0.setGeometry(QtCore.QRect(10, 50, 121, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnE0.setFont(font)
        self.btnE0.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
""))
        self.btnE0.setObjectName(_fromUtf8("btnE0"))
        self.btnStartScan = QtGui.QPushButton(self.tabCmd)
        self.btnStartScan.setEnabled(True)
        self.btnStartScan.setGeometry(QtCore.QRect(10, 110, 121, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnStartScan.setFont(font)
        self.btnStartScan.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);\n"
"background-color: rgb(255, 255, 255);"))
        self.btnStartScan.setObjectName(_fromUtf8("btnStartScan"))
        self.showItems = QtGui.QComboBox(self.tabCmd)
        self.showItems.setGeometry(QtCore.QRect(870, 70, 121, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.showItems.setFont(font)
        self.showItems.setFocusPolicy(QtCore.Qt.NoFocus)
        self.showItems.setObjectName(_fromUtf8("showItems"))
        self.showItems.addItem(_fromUtf8(""))
        self.showItems.addItem(_fromUtf8(""))
        self.showItems.addItem(_fromUtf8(""))
        self.showItems.addItem(_fromUtf8(""))
        self.showItems.addItem(_fromUtf8(""))
        self.showItems.addItem(_fromUtf8(""))
        self.btnStopScan = QtGui.QPushButton(self.tabCmd)
        self.btnStopScan.setEnabled(True)
        self.btnStopScan.setGeometry(QtCore.QRect(10, 170, 121, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnStopScan.setFont(font)
        self.btnStopScan.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
""))
        self.btnStopScan.setObjectName(_fromUtf8("btnStopScan"))
        self.gridLayoutWidget = QtGui.QWidget(self.tabCmd)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(230, 10, 431, 201))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_44 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.horizontalLayout_23.addWidget(self.label_44)
        self.doublePre1Start = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doublePre1Start.sizePolicy().hasHeightForWidth())
        self.doublePre1Start.setSizePolicy(sizePolicy)
        self.doublePre1Start.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doublePre1Start.setWrapping(False)
        self.doublePre1Start.setFrame(True)
        self.doublePre1Start.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doublePre1Start.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doublePre1Start.setDecimals(3)
        self.doublePre1Start.setMinimum(-999.999)
        self.doublePre1Start.setMaximum(999.999)
        self.doublePre1Start.setSingleStep(0.0)
        self.doublePre1Start.setProperty("value", -200.0)
        self.doublePre1Start.setObjectName(_fromUtf8("doublePre1Start"))
        self.horizontalLayout_23.addWidget(self.doublePre1Start)
        self.doublePre1Stop = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doublePre1Stop.sizePolicy().hasHeightForWidth())
        self.doublePre1Stop.setSizePolicy(sizePolicy)
        self.doublePre1Stop.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doublePre1Stop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doublePre1Stop.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doublePre1Stop.setDecimals(3)
        self.doublePre1Stop.setMinimum(-999.999)
        self.doublePre1Stop.setMaximum(999.999)
        self.doublePre1Stop.setSingleStep(0.0)
        self.doublePre1Stop.setProperty("value", -50.0)
        self.doublePre1Stop.setObjectName(_fromUtf8("doublePre1Stop"))
        self.horizontalLayout_23.addWidget(self.doublePre1Stop)
        self.doublePre1Step = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doublePre1Step.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doublePre1Step.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doublePre1Step.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doublePre1Step.setDecimals(3)
        self.doublePre1Step.setMinimum(0.01)
        self.doublePre1Step.setMaximum(999.999)
        self.doublePre1Step.setSingleStep(0.0)
        self.doublePre1Step.setProperty("value", 5.0)
        self.doublePre1Step.setObjectName(_fromUtf8("doublePre1Step"))
        self.horizontalLayout_23.addWidget(self.doublePre1Step)
        self.doublePre1Time = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doublePre1Time.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doublePre1Time.setAlignment(QtCore.Qt.AlignCenter)
        self.doublePre1Time.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doublePre1Time.setDecimals(2)
        self.doublePre1Time.setMinimum(0.01)
        self.doublePre1Time.setMaximum(500.0)
        self.doublePre1Time.setSingleStep(0.0)
        self.doublePre1Time.setProperty("value", 1.0)
        self.doublePre1Time.setObjectName(_fromUtf8("doublePre1Time"))
        self.horizontalLayout_23.addWidget(self.doublePre1Time)
        self.labelPre1Units = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPre1Units.sizePolicy().hasHeightForWidth())
        self.labelPre1Units.setSizePolicy(sizePolicy)
        self.labelPre1Units.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPre1Units.setObjectName(_fromUtf8("labelPre1Units"))
        self.horizontalLayout_23.addWidget(self.labelPre1Units)
        self.gridLayout_3.addLayout(self.horizontalLayout_23, 2, 0, 1, 1)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_54 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_54.sizePolicy().hasHeightForWidth())
        self.label_54.setSizePolicy(sizePolicy)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.horizontalLayout_28.addWidget(self.label_54)
        self.doubleXAFS2Start = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleXAFS2Start.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXAFS2Start.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleXAFS2Start.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXAFS2Start.setDecimals(3)
        self.doubleXAFS2Start.setMinimum(1.0)
        self.doubleXAFS2Start.setMaximum(9999.0)
        self.doubleXAFS2Start.setSingleStep(0.0)
        self.doubleXAFS2Start.setProperty("value", 549.0)
        self.doubleXAFS2Start.setObjectName(_fromUtf8("doubleXAFS2Start"))
        self.horizontalLayout_28.addWidget(self.doubleXAFS2Start)
        self.doubleXAFS2Stop = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleXAFS2Stop.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXAFS2Stop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleXAFS2Stop.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXAFS2Stop.setDecimals(3)
        self.doubleXAFS2Stop.setMinimum(1.0)
        self.doubleXAFS2Stop.setMaximum(9999.0)
        self.doubleXAFS2Stop.setSingleStep(0.0)
        self.doubleXAFS2Stop.setProperty("value", 976.0)
        self.doubleXAFS2Stop.setObjectName(_fromUtf8("doubleXAFS2Stop"))
        self.horizontalLayout_28.addWidget(self.doubleXAFS2Stop)
        self.doubleXAFS2Step = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleXAFS2Step.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXAFS2Step.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleXAFS2Step.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXAFS2Step.setDecimals(3)
        self.doubleXAFS2Step.setMinimum(0.01)
        self.doubleXAFS2Step.setMaximum(999.999)
        self.doubleXAFS2Step.setSingleStep(0.0)
        self.doubleXAFS2Step.setProperty("value", 0.05)
        self.doubleXAFS2Step.setObjectName(_fromUtf8("doubleXAFS2Step"))
        self.horizontalLayout_28.addWidget(self.doubleXAFS2Step)
        self.doubleXAFS2Time = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleXAFS2Time.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXAFS2Time.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleXAFS2Time.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXAFS2Time.setDecimals(2)
        self.doubleXAFS2Time.setMinimum(0.01)
        self.doubleXAFS2Time.setMaximum(500.0)
        self.doubleXAFS2Time.setSingleStep(0.0)
        self.doubleXAFS2Time.setProperty("value", 1.0)
        self.doubleXAFS2Time.setObjectName(_fromUtf8("doubleXAFS2Time"))
        self.horizontalLayout_28.addWidget(self.doubleXAFS2Time)
        self.XAFS2Units = QtGui.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XAFS2Units.sizePolicy().hasHeightForWidth())
        self.XAFS2Units.setSizePolicy(sizePolicy)
        self.XAFS2Units.setFocusPolicy(QtCore.Qt.NoFocus)
        self.XAFS2Units.setMaxVisibleItems(2)
        self.XAFS2Units.setMaxCount(2)
        self.XAFS2Units.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.XAFS2Units.setFrame(True)
        self.XAFS2Units.setObjectName(_fromUtf8("XAFS2Units"))
        self.XAFS2Units.addItem(_fromUtf8(""))
        self.XAFS2Units.addItem(_fromUtf8(""))
        self.horizontalLayout_28.addWidget(self.XAFS2Units)
        self.gridLayout_3.addLayout(self.horizontalLayout_28, 6, 0, 1, 1)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_50 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_50.sizePolicy().hasHeightForWidth())
        self.label_50.setSizePolicy(sizePolicy)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.horizontalLayout_26.addWidget(self.label_50)
        self.doubleXANESStart = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleXANESStart.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXANESStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleXANESStart.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXANESStart.setDecimals(3)
        self.doubleXANESStart.setMinimum(-999.999)
        self.doubleXANESStart.setMaximum(999.999)
        self.doubleXANESStart.setSingleStep(0.0)
        self.doubleXANESStart.setProperty("value", -10.0)
        self.doubleXANESStart.setObjectName(_fromUtf8("doubleXANESStart"))
        self.horizontalLayout_26.addWidget(self.doubleXANESStart)
        self.doubleXANESStop = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleXANESStop.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXANESStop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleXANESStop.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXANESStop.setDecimals(3)
        self.doubleXANESStop.setMinimum(-999.999)
        self.doubleXANESStop.setMaximum(999.999)
        self.doubleXANESStop.setSingleStep(0.0)
        self.doubleXANESStop.setProperty("value", 40.0)
        self.doubleXANESStop.setObjectName(_fromUtf8("doubleXANESStop"))
        self.horizontalLayout_26.addWidget(self.doubleXANESStop)
        self.doubleXANESStep = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleXANESStep.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXANESStep.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleXANESStep.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXANESStep.setDecimals(3)
        self.doubleXANESStep.setMinimum(0.01)
        self.doubleXANESStep.setMaximum(999.999)
        self.doubleXANESStep.setSingleStep(0.0)
        self.doubleXANESStep.setProperty("value", 0.4)
        self.doubleXANESStep.setObjectName(_fromUtf8("doubleXANESStep"))
        self.horizontalLayout_26.addWidget(self.doubleXANESStep)
        self.doubleXANESTime = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleXANESTime.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXANESTime.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleXANESTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXANESTime.setDecimals(2)
        self.doubleXANESTime.setMinimum(0.01)
        self.doubleXANESTime.setMaximum(500.0)
        self.doubleXANESTime.setSingleStep(0.0)
        self.doubleXANESTime.setProperty("value", 1.0)
        self.doubleXANESTime.setObjectName(_fromUtf8("doubleXANESTime"))
        self.horizontalLayout_26.addWidget(self.doubleXANESTime)
        self.labelXANESUnits = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelXANESUnits.sizePolicy().hasHeightForWidth())
        self.labelXANESUnits.setSizePolicy(sizePolicy)
        self.labelXANESUnits.setStyleSheet(_fromUtf8(""))
        self.labelXANESUnits.setAlignment(QtCore.Qt.AlignCenter)
        self.labelXANESUnits.setObjectName(_fromUtf8("labelXANESUnits"))
        self.horizontalLayout_26.addWidget(self.labelXANESUnits)
        self.gridLayout_3.addLayout(self.horizontalLayout_26, 4, 0, 1, 1)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.label_55 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_55.sizePolicy().hasHeightForWidth())
        self.label_55.setSizePolicy(sizePolicy)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.horizontalLayout_29.addWidget(self.label_55)
        self.doubleXAFS3Start = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleXAFS3Start.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXAFS3Start.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleXAFS3Start.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXAFS3Start.setDecimals(3)
        self.doubleXAFS3Start.setMinimum(1.0)
        self.doubleXAFS3Start.setMaximum(9999.0)
        self.doubleXAFS3Start.setSingleStep(0.0)
        self.doubleXAFS3Start.setProperty("value", 976.0)
        self.doubleXAFS3Start.setObjectName(_fromUtf8("doubleXAFS3Start"))
        self.horizontalLayout_29.addWidget(self.doubleXAFS3Start)
        self.doubleXAFS3Stop = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleXAFS3Stop.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXAFS3Stop.setStatusTip(_fromUtf8(""))
        self.doubleXAFS3Stop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleXAFS3Stop.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXAFS3Stop.setDecimals(3)
        self.doubleXAFS3Stop.setMinimum(1.0)
        self.doubleXAFS3Stop.setMaximum(9999.0)
        self.doubleXAFS3Stop.setSingleStep(0.0)
        self.doubleXAFS3Stop.setProperty("value", 1524.0)
        self.doubleXAFS3Stop.setObjectName(_fromUtf8("doubleXAFS3Stop"))
        self.horizontalLayout_29.addWidget(self.doubleXAFS3Stop)
        self.doubleXAFS3Step = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleXAFS3Step.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXAFS3Step.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleXAFS3Step.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXAFS3Step.setDecimals(3)
        self.doubleXAFS3Step.setMinimum(0.01)
        self.doubleXAFS3Step.setMaximum(999.999)
        self.doubleXAFS3Step.setSingleStep(0.0)
        self.doubleXAFS3Step.setProperty("value", 0.07)
        self.doubleXAFS3Step.setObjectName(_fromUtf8("doubleXAFS3Step"))
        self.horizontalLayout_29.addWidget(self.doubleXAFS3Step)
        self.doubleXAFS3Time = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleXAFS3Time.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXAFS3Time.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleXAFS3Time.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXAFS3Time.setDecimals(2)
        self.doubleXAFS3Time.setMinimum(0.01)
        self.doubleXAFS3Time.setMaximum(500.0)
        self.doubleXAFS3Time.setSingleStep(0.0)
        self.doubleXAFS3Time.setProperty("value", 1.0)
        self.doubleXAFS3Time.setObjectName(_fromUtf8("doubleXAFS3Time"))
        self.horizontalLayout_29.addWidget(self.doubleXAFS3Time)
        self.XAFS3Units = QtGui.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XAFS3Units.sizePolicy().hasHeightForWidth())
        self.XAFS3Units.setSizePolicy(sizePolicy)
        self.XAFS3Units.setFocusPolicy(QtCore.Qt.NoFocus)
        self.XAFS3Units.setMaxVisibleItems(2)
        self.XAFS3Units.setMaxCount(2)
        self.XAFS3Units.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.XAFS3Units.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.XAFS3Units.setObjectName(_fromUtf8("XAFS3Units"))
        self.XAFS3Units.addItem(_fromUtf8(""))
        self.XAFS3Units.addItem(_fromUtf8(""))
        self.horizontalLayout_29.addWidget(self.XAFS3Units)
        self.gridLayout_3.addLayout(self.horizontalLayout_29, 7, 0, 1, 1)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_48 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_48.sizePolicy().hasHeightForWidth())
        self.label_48.setSizePolicy(sizePolicy)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.horizontalLayout_25.addWidget(self.label_48)
        self.doublePre2Start = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doublePre2Start.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doublePre2Start.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doublePre2Start.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doublePre2Start.setDecimals(3)
        self.doublePre2Start.setMinimum(-999.999)
        self.doublePre2Start.setMaximum(999.999)
        self.doublePre2Start.setSingleStep(0.0)
        self.doublePre2Start.setProperty("value", -50.0)
        self.doublePre2Start.setObjectName(_fromUtf8("doublePre2Start"))
        self.horizontalLayout_25.addWidget(self.doublePre2Start)
        self.doublePre2Stop = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doublePre2Stop.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doublePre2Stop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doublePre2Stop.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doublePre2Stop.setDecimals(3)
        self.doublePre2Stop.setMinimum(-999.999)
        self.doublePre2Stop.setMaximum(999.999)
        self.doublePre2Stop.setSingleStep(0.0)
        self.doublePre2Stop.setProperty("value", -10.0)
        self.doublePre2Stop.setObjectName(_fromUtf8("doublePre2Stop"))
        self.horizontalLayout_25.addWidget(self.doublePre2Stop)
        self.doublePre2Step = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doublePre2Step.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doublePre2Step.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doublePre2Step.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doublePre2Step.setDecimals(3)
        self.doublePre2Step.setMinimum(0.01)
        self.doublePre2Step.setMaximum(999.999)
        self.doublePre2Step.setSingleStep(0.0)
        self.doublePre2Step.setProperty("value", 1.0)
        self.doublePre2Step.setObjectName(_fromUtf8("doublePre2Step"))
        self.horizontalLayout_25.addWidget(self.doublePre2Step)
        self.doublePre2Time = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doublePre2Time.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doublePre2Time.setAlignment(QtCore.Qt.AlignCenter)
        self.doublePre2Time.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doublePre2Time.setDecimals(2)
        self.doublePre2Time.setMinimum(0.01)
        self.doublePre2Time.setMaximum(500.0)
        self.doublePre2Time.setSingleStep(0.0)
        self.doublePre2Time.setProperty("value", 1.0)
        self.doublePre2Time.setObjectName(_fromUtf8("doublePre2Time"))
        self.horizontalLayout_25.addWidget(self.doublePre2Time)
        self.labelPre2Units = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPre2Units.sizePolicy().hasHeightForWidth())
        self.labelPre2Units.setSizePolicy(sizePolicy)
        self.labelPre2Units.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPre2Units.setObjectName(_fromUtf8("labelPre2Units"))
        self.horizontalLayout_25.addWidget(self.labelPre2Units)
        self.gridLayout_3.addLayout(self.horizontalLayout_25, 3, 0, 1, 1)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_22.addWidget(self.label)
        self.label_38 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.horizontalLayout_22.addWidget(self.label_38)
        self.label_39 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_39.sizePolicy().hasHeightForWidth())
        self.label_39.setSizePolicy(sizePolicy)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.horizontalLayout_22.addWidget(self.label_39)
        self.label_40 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_40.sizePolicy().hasHeightForWidth())
        self.label_40.setSizePolicy(sizePolicy)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.horizontalLayout_22.addWidget(self.label_40)
        self.label_42 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_42.sizePolicy().hasHeightForWidth())
        self.label_42.setSizePolicy(sizePolicy)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.horizontalLayout_22.addWidget(self.label_42)
        self.label_43 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.horizontalLayout_22.addWidget(self.label_43)
        self.gridLayout_3.addLayout(self.horizontalLayout_22, 1, 0, 1, 1)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_52 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_52.sizePolicy().hasHeightForWidth())
        self.label_52.setSizePolicy(sizePolicy)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.horizontalLayout_27.addWidget(self.label_52)
        self.doubleXAFS1Start = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleXAFS1Start.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXAFS1Start.setWhatsThis(_fromUtf8(""))
        self.doubleXAFS1Start.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleXAFS1Start.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXAFS1Start.setDecimals(3)
        self.doubleXAFS1Start.setMinimum(-999.999)
        self.doubleXAFS1Start.setMaximum(999.999)
        self.doubleXAFS1Start.setSingleStep(0.0)
        self.doubleXAFS1Start.setProperty("value", 40.0)
        self.doubleXAFS1Start.setObjectName(_fromUtf8("doubleXAFS1Start"))
        self.horizontalLayout_27.addWidget(self.doubleXAFS1Start)
        self.doubleXAFS1Stop = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleXAFS1Stop.setMouseTracking(False)
        self.doubleXAFS1Stop.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXAFS1Stop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleXAFS1Stop.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXAFS1Stop.setDecimals(3)
        self.doubleXAFS1Stop.setMinimum(1.0)
        self.doubleXAFS1Stop.setMaximum(9999.0)
        self.doubleXAFS1Stop.setSingleStep(0.0)
        self.doubleXAFS1Stop.setProperty("value", 549.0)
        self.doubleXAFS1Stop.setObjectName(_fromUtf8("doubleXAFS1Stop"))
        self.horizontalLayout_27.addWidget(self.doubleXAFS1Stop)
        self.doubleXAFS1Step = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleXAFS1Step.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXAFS1Step.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleXAFS1Step.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXAFS1Step.setDecimals(3)
        self.doubleXAFS1Step.setMinimum(0.01)
        self.doubleXAFS1Step.setMaximum(999.999)
        self.doubleXAFS1Step.setSingleStep(0.0)
        self.doubleXAFS1Step.setProperty("value", 0.03)
        self.doubleXAFS1Step.setObjectName(_fromUtf8("doubleXAFS1Step"))
        self.horizontalLayout_27.addWidget(self.doubleXAFS1Step)
        self.doubleXAFS1Time = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleXAFS1Time.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleXAFS1Time.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleXAFS1Time.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleXAFS1Time.setDecimals(2)
        self.doubleXAFS1Time.setMinimum(0.01)
        self.doubleXAFS1Time.setMaximum(500.0)
        self.doubleXAFS1Time.setSingleStep(0.0)
        self.doubleXAFS1Time.setProperty("value", 1.0)
        self.doubleXAFS1Time.setObjectName(_fromUtf8("doubleXAFS1Time"))
        self.horizontalLayout_27.addWidget(self.doubleXAFS1Time)
        self.XAFS1Units = QtGui.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XAFS1Units.sizePolicy().hasHeightForWidth())
        self.XAFS1Units.setSizePolicy(sizePolicy)
        self.XAFS1Units.setMinimumSize(QtCore.QSize(66, 0))
        self.XAFS1Units.setFocusPolicy(QtCore.Qt.NoFocus)
        self.XAFS1Units.setMaxVisibleItems(2)
        self.XAFS1Units.setMaxCount(2)
        self.XAFS1Units.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.XAFS1Units.setObjectName(_fromUtf8("XAFS1Units"))
        self.XAFS1Units.addItem(_fromUtf8(""))
        self.XAFS1Units.addItem(_fromUtf8(""))
        self.horizontalLayout_27.addWidget(self.XAFS1Units)
        self.gridLayout_3.addLayout(self.horizontalLayout_27, 5, 0, 1, 1)
        self.doubleE0 = QtGui.QDoubleSpinBox(self.tabCmd)
        self.doubleE0.setGeometry(QtCore.QRect(10, 10, 121, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleE0.sizePolicy().hasHeightForWidth())
        self.doubleE0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.doubleE0.setFont(font)
        self.doubleE0.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.doubleE0.setWrapping(False)
        self.doubleE0.setFrame(True)
        self.doubleE0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleE0.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleE0.setDecimals(3)
        self.doubleE0.setMinimum(4000.0)
        self.doubleE0.setMaximum(99999.0)
        self.doubleE0.setSingleStep(0.0)
        self.doubleE0.setProperty("value", 7112.0)
        self.doubleE0.setObjectName(_fromUtf8("doubleE0"))
        self.layoutWidget = QtGui.QWidget(self.tabCmd)
        self.layoutWidget.setGeometry(QtCore.QRect(680, 10, 121, 201))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.dispEnergy = QtGui.QLCDNumber(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dispEnergy.sizePolicy().hasHeightForWidth())
        self.dispEnergy.setSizePolicy(sizePolicy)
        self.dispEnergy.setMinimumSize(QtCore.QSize(119, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.dispEnergy.setFont(font)
        self.dispEnergy.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.dispEnergy.setLineWidth(0)
        self.dispEnergy.setSmallDecimalPoint(False)
        self.dispEnergy.setNumDigits(7)
        self.dispEnergy.setDigitCount(7)
        self.dispEnergy.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.dispEnergy.setProperty("intValue", 0)
        self.dispEnergy.setObjectName(_fromUtf8("dispEnergy"))
        self.verticalLayout.addWidget(self.dispEnergy)
        self.dispIo = QtGui.QLCDNumber(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dispIo.setFont(font)
        self.dispIo.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.dispIo.setLineWidth(0)
        self.dispIo.setSmallDecimalPoint(False)
        self.dispIo.setNumDigits(7)
        self.dispIo.setDigitCount(7)
        self.dispIo.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.dispIo.setProperty("intValue", 0)
        self.dispIo.setObjectName(_fromUtf8("dispIo"))
        self.verticalLayout.addWidget(self.dispIo)
        self.dispIt = QtGui.QLCDNumber(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dispIt.setFont(font)
        self.dispIt.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.dispIt.setLineWidth(0)
        self.dispIt.setSmallDecimalPoint(False)
        self.dispIt.setNumDigits(7)
        self.dispIt.setDigitCount(7)
        self.dispIt.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.dispIt.setProperty("intValue", 0)
        self.dispIt.setObjectName(_fromUtf8("dispIt"))
        self.verticalLayout.addWidget(self.dispIt)
        self.dispIf = QtGui.QLCDNumber(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dispIf.setFont(font)
        self.dispIf.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.dispIf.setLineWidth(0)
        self.dispIf.setSmallDecimalPoint(False)
        self.dispIf.setNumDigits(7)
        self.dispIf.setDigitCount(7)
        self.dispIf.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.dispIf.setProperty("intValue", 0)
        self.dispIf.setObjectName(_fromUtf8("dispIf"))
        self.verticalLayout.addWidget(self.dispIf)
        self.dispIr = QtGui.QLCDNumber(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dispIr.setFont(font)
        self.dispIr.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.dispIr.setLineWidth(0)
        self.dispIr.setSmallDecimalPoint(False)
        self.dispIr.setNumDigits(7)
        self.dispIr.setDigitCount(7)
        self.dispIr.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.dispIr.setProperty("intValue", 0)
        self.dispIr.setObjectName(_fromUtf8("dispIr"))
        self.verticalLayout.addWidget(self.dispIr)
        self.dispSRbeam = QtGui.QLCDNumber(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dispSRbeam.sizePolicy().hasHeightForWidth())
        self.dispSRbeam.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dispSRbeam.setFont(font)
        self.dispSRbeam.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.dispSRbeam.setLineWidth(0)
        self.dispSRbeam.setSmallDecimalPoint(False)
        self.dispSRbeam.setNumDigits(7)
        self.dispSRbeam.setDigitCount(7)
        self.dispSRbeam.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.dispSRbeam.setProperty("intValue", 0)
        self.dispSRbeam.setObjectName(_fromUtf8("dispSRbeam"))
        self.verticalLayout.addWidget(self.dispSRbeam)
        self.layoutWidget1 = QtGui.QWidget(self.tabCmd)
        self.layoutWidget1.setGeometry(QtCore.QRect(800, 10, 40, 201))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_2.addWidget(self.label_8)
        self.label_9 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_2.addWidget(self.label_9)
        self.label_10 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_2.addWidget(self.label_10)
        self.label_11 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_2.addWidget(self.label_11)
        self.layoutWidget2 = QtGui.QWidget(self.tabCmd)
        self.layoutWidget2.setGeometry(QtCore.QRect(140, 160, 71, 51))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_12 = QtGui.QLabel(self.layoutWidget2)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_5.addWidget(self.label_12)
        self.selectRegion = QtGui.QComboBox(self.layoutWidget2)
        self.selectRegion.setFocusPolicy(QtCore.Qt.NoFocus)
        self.selectRegion.setEditable(False)
        self.selectRegion.setObjectName(_fromUtf8("selectRegion"))
        self.selectRegion.addItem(_fromUtf8(""))
        self.selectRegion.addItem(_fromUtf8(""))
        self.selectRegion.addItem(_fromUtf8(""))
        self.selectRegion.addItem(_fromUtf8(""))
        self.selectRegion.addItem(_fromUtf8(""))
        self.verticalLayout_5.addWidget(self.selectRegion)
        self.layoutWidget_2 = QtGui.QWidget(self.tabCmd)
        self.layoutWidget_2.setGeometry(QtCore.QRect(140, 10, 71, 51))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.LabelElement = QtGui.QLabel(self.layoutWidget_2)
        self.LabelElement.setObjectName(_fromUtf8("LabelElement"))
        self.verticalLayout_7.addWidget(self.LabelElement)
        self.elements = QtGui.QComboBox(self.layoutWidget_2)
        self.elements.setFocusPolicy(QtCore.Qt.NoFocus)
        self.elements.setMaxVisibleItems(200)
        self.elements.setObjectName(_fromUtf8("elements"))
        self.verticalLayout_7.addWidget(self.elements)
        self.layoutWidget_3 = QtGui.QWidget(self.tabCmd)
        self.layoutWidget_3.setGeometry(QtCore.QRect(140, 80, 71, 61))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.NOS = QtGui.QLabel(self.layoutWidget_3)
        self.NOS.setLineWidth(2)
        self.NOS.setIndent(-1)
        self.NOS.setObjectName(_fromUtf8("NOS"))
        self.verticalLayout_8.addWidget(self.NOS)
        self.numberOfscans = QtGui.QSpinBox(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.numberOfscans.setFont(font)
        self.numberOfscans.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.numberOfscans.setFrame(True)
        self.numberOfscans.setAlignment(QtCore.Qt.AlignCenter)
        self.numberOfscans.setMinimum(1)
        self.numberOfscans.setMaximum(100)
        self.numberOfscans.setObjectName(_fromUtf8("numberOfscans"))
        self.verticalLayout_8.addWidget(self.numberOfscans)
        self.line_2 = QtGui.QFrame(self.tabCmd)
        self.line_2.setGeometry(QtCore.QRect(210, -20, 20, 271))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.tabCmd)
        self.line_3.setGeometry(QtCore.QRect(660, -20, 20, 271))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(self.tabCmd)
        self.line_4.setGeometry(QtCore.QRect(840, -20, 20, 271))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.widget = QtGui.QWidget(self.tabCmd)
        self.widget.setGeometry(QtCore.QRect(870, 10, 71, 48))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.plotHistory = QtGui.QLabel(self.widget)
        self.plotHistory.setObjectName(_fromUtf8("plotHistory"))
        self.verticalLayout_6.addWidget(self.plotHistory)
        self.history = QtGui.QSpinBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.history.setFont(font)
        self.history.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.history.setFrame(True)
        self.history.setAlignment(QtCore.Qt.AlignCenter)
        self.history.setMinimum(1)
        self.history.setMaximum(10)
        self.history.setObjectName(_fromUtf8("history"))
        self.verticalLayout_6.addWidget(self.history)
        self.widget1 = QtGui.QWidget(self.tabCmd)
        self.widget1.setGeometry(QtCore.QRect(870, 160, 121, 51))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.fileLabel = QtGui.QLabel(self.widget1)
        self.fileLabel.setObjectName(_fromUtf8("fileLabel"))
        self.verticalLayout_10.addWidget(self.fileLabel)
        self.enterFileName = QtGui.QLineEdit(self.widget1)
        self.enterFileName.setInputMask(_fromUtf8(""))
        self.enterFileName.setText(_fromUtf8(""))
        self.enterFileName.setObjectName(_fromUtf8("enterFileName"))
        self.verticalLayout_10.addWidget(self.enterFileName)
        self.tabControl.addTab(self.tabCmd, _fromUtf8(""))
        self.tabSerial = QtGui.QWidget()
        self.tabSerial.setObjectName(_fromUtf8("tabSerial"))
        self.layoutWidget3 = QtGui.QWidget(self.tabSerial)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 20, 211, 76))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(self.layoutWidget3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.cbPorts = QtGui.QComboBox(self.layoutWidget3)
        self.cbPorts.setMaxVisibleItems(10)
        self.cbPorts.setObjectName(_fromUtf8("cbPorts"))
        self.cbPorts.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.cbPorts)
        self.btnRescan = QtGui.QPushButton(self.layoutWidget3)
        self.btnRescan.setObjectName(_fromUtf8("btnRescan"))
        self.verticalLayout_3.addWidget(self.btnRescan)
        self.layoutWidget4 = QtGui.QWidget(self.tabSerial)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 100, 211, 46))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_4 = QtGui.QLabel(self.layoutWidget4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.cbBaudrate = QtGui.QComboBox(self.layoutWidget4)
        self.cbBaudrate.setObjectName(_fromUtf8("cbBaudrate"))
        self.cbBaudrate.addItem(_fromUtf8(""))
        self.cbBaudrate.addItem(_fromUtf8(""))
        self.cbBaudrate.addItem(_fromUtf8(""))
        self.cbBaudrate.addItem(_fromUtf8(""))
        self.cbBaudrate.addItem(_fromUtf8(""))
        self.cbBaudrate.addItem(_fromUtf8(""))
        self.cbBaudrate.addItem(_fromUtf8(""))
        self.cbBaudrate.addItem(_fromUtf8(""))
        self.cbBaudrate.addItem(_fromUtf8(""))
        self.verticalLayout_4.addWidget(self.cbBaudrate)
        self.layoutWidget5 = QtGui.QWidget(self.tabSerial)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 150, 211, 27))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.layoutWidget5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.btnSerialStart = QtGui.QPushButton(self.layoutWidget5)
        self.btnSerialStart.setEnabled(False)
        self.btnSerialStart.setObjectName(_fromUtf8("btnSerialStart"))
        self.horizontalLayout_3.addWidget(self.btnSerialStart)
        self.widget2 = QtGui.QWidget(self.tabSerial)
        self.widget2.setGeometry(QtCore.QRect(370, 40, 141, 81))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.widget2)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.labelOkay = QtGui.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelOkay.setFont(font)
        self.labelOkay.setObjectName(_fromUtf8("labelOkay"))
        self.verticalLayout_9.addWidget(self.labelOkay)
        self.pbOkay = QtGui.QPushButton(self.widget2)
        self.pbOkay.setObjectName(_fromUtf8("pbOkay"))
        self.verticalLayout_9.addWidget(self.pbOkay)
        self.tabControl.addTab(self.tabSerial, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabControl, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuSetting = QtGui.QMenu(self.menubar)
        self.menuSetting.setObjectName(_fromUtf8("menuSetting"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        self.statusbar.setFont(font)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionClear = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/edit-clear-3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClear.setIcon(icon)
        self.actionClear.setObjectName(_fromUtf8("actionClear"))
        self.actionSave = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/document-save-5.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon1)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionDir = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/system-run-3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDir.setIcon(icon2)
        self.actionDir.setObjectName(_fromUtf8("actionDir"))
        self.actionExit = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/application-exit-2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon3)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icons/help-about-3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon4)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionClear)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionAbout)
        self.menuSetting.addAction(self.actionDir)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.toolBar.addAction(self.actionClear)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionDir)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAbout)

        self.retranslateUi(MainWindow)
        self.tabControl.setCurrentIndex(0)
        self.XAFS2Units.setCurrentIndex(1)
        self.XAFS3Units.setCurrentIndex(1)
        self.XAFS1Units.setCurrentIndex(1)
        self.selectRegion.setCurrentIndex(3)
        self.elements.setCurrentIndex(-1)
        self.cbBaudrate.setCurrentIndex(7)
        QtCore.QObject.connect(self.doublePre1Stop, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.doublePre2Start.setValue)
        QtCore.QObject.connect(self.doublePre2Start, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.doublePre1Stop.setValue)
        QtCore.QObject.connect(self.doublePre2Stop, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.doubleXANESStart.setValue)
        QtCore.QObject.connect(self.doubleXANESStart, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.doublePre2Stop.setValue)
        QtCore.QObject.connect(self.doubleXANESStop, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.doubleXAFS1Start.setValue)
        QtCore.QObject.connect(self.doubleXAFS1Start, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.doubleXANESStop.setValue)
        QtCore.QObject.connect(self.doubleXAFS1Stop, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.doubleXAFS2Start.setValue)
        QtCore.QObject.connect(self.doubleXAFS2Start, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.doubleXAFS1Stop.setValue)
        QtCore.QObject.connect(self.doubleXAFS2Stop, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.doubleXAFS3Start.setValue)
        QtCore.QObject.connect(self.doubleXAFS3Start, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.doubleXAFS2Stop.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "PyDataLogger V1.0", None))
        self.label_2.setText(_translate("MainWindow", "Command:", None))
        self.btnE0.setText(_translate("MainWindow", "MOVE to E0", None))
        self.btnStartScan.setText(_translate("MainWindow", "SCAN Start", None))
        self.showItems.setItemText(0, _translate("MainWindow", "Transmittance", None))
        self.showItems.setItemText(1, _translate("MainWindow", "Floulescence", None))
        self.showItems.setItemText(2, _translate("MainWindow", "Io only", None))
        self.showItems.setItemText(3, _translate("MainWindow", "It only", None))
        self.showItems.setItemText(4, _translate("MainWindow", "If only", None))
        self.showItems.setItemText(5, _translate("MainWindow", "Ir only", None))
        self.btnStopScan.setText(_translate("MainWindow", "SCAN Stop", None))
        self.label_44.setText(_translate("MainWindow", "Pre-Edge1", None))
        self.labelPre1Units.setText(_translate("MainWindow", "eV", None))
        self.label_54.setText(_translate("MainWindow", "XAFS2", None))
        self.doubleXAFS2Start.setToolTip(_translate("MainWindow", "<html><head/><body><p>12k --> 549eV</p></body></html>", None))
        self.doubleXAFS2Stop.setToolTip(_translate("MainWindow", "<html><head/><body><p>16k --> 976eV</p></body></html>", None))
        self.doubleXAFS2Step.setToolTip(_translate("MainWindow", "<html><head/><body><p>Default 0.05</p></body></html>", None))
        self.XAFS2Units.setItemText(0, _translate("MainWindow", "eV", None))
        self.XAFS2Units.setItemText(1, _translate("MainWindow", "k", None))
        self.label_50.setText(_translate("MainWindow", "XANES", None))
        self.doubleXANESStop.setToolTip(_translate("MainWindow", "<html><head/><body><p>3.24k--> 40eV</p></body></html>", None))
        self.labelXANESUnits.setText(_translate("MainWindow", "eV", None))
        self.label_55.setText(_translate("MainWindow", "XAFS3", None))
        self.doubleXAFS3Start.setToolTip(_translate("MainWindow", "<html><head/><body><p>16k --> 976eV</p></body></html>", None))
        self.doubleXAFS3Stop.setToolTip(_translate("MainWindow", "<html><head/><body><p>\'20K --> 1524eV\'</p></body></html>", None))
        self.doubleXAFS3Stop.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>\'20k --> 1524eV\'</p></body></html>", None))
        self.doubleXAFS3Step.setToolTip(_translate("MainWindow", "<html><head/><body><p>Default 0.07</p></body></html>", None))
        self.XAFS3Units.setItemText(0, _translate("MainWindow", "eV", None))
        self.XAFS3Units.setItemText(1, _translate("MainWindow", "k", None))
        self.label_48.setText(_translate("MainWindow", "Pre-Edge2", None))
        self.labelPre2Units.setText(_translate("MainWindow", "eV", None))
        self.label.setText(_translate("MainWindow", "Region", None))
        self.label_38.setText(_translate("MainWindow", "Start", None))
        self.label_39.setText(_translate("MainWindow", "Stop", None))
        self.label_40.setText(_translate("MainWindow", "Step", None))
        self.label_42.setText(_translate("MainWindow", "Time(s)", None))
        self.label_43.setText(_translate("MainWindow", "Units", None))
        self.label_52.setText(_translate("MainWindow", "XAFS1", None))
        self.doubleXAFS1Start.setToolTip(_translate("MainWindow", "<html><head/><body><p>3.24k--> 40eV</p></body></html>", None))
        self.doubleXAFS1Stop.setToolTip(_translate("MainWindow", "<html><head/><body><p>12k --> 549eV</p></body></html>", None))
        self.doubleXAFS1Step.setToolTip(_translate("MainWindow", "<html><head/><body><p>Default 0.03</p></body></html>", None))
        self.XAFS1Units.setItemText(0, _translate("MainWindow", "eV", None))
        self.XAFS1Units.setItemText(1, _translate("MainWindow", "k", None))
        self.label_6.setText(_translate("MainWindow", "[eV]", None))
        self.label_7.setText(_translate("MainWindow", "Io", None))
        self.label_8.setText(_translate("MainWindow", "It", None))
        self.label_9.setText(_translate("MainWindow", "If", None))
        self.label_10.setText(_translate("MainWindow", "Ir", None))
        self.label_11.setText(_translate("MainWindow", "[mA]", None))
        self.label_12.setText(_translate("MainWindow", "# region", None))
        self.selectRegion.setItemText(0, _translate("MainWindow", "Pre2", None))
        self.selectRegion.setItemText(1, _translate("MainWindow", "XANES", None))
        self.selectRegion.setItemText(2, _translate("MainWindow", "XAFS1", None))
        self.selectRegion.setItemText(3, _translate("MainWindow", "XAFS2", None))
        self.selectRegion.setItemText(4, _translate("MainWindow", "XAFS3", None))
        self.LabelElement.setText(_translate("MainWindow", "elements", None))
        self.NOS.setText(_translate("MainWindow", "# scans", None))
        self.plotHistory.setText(_translate("MainWindow", "# History", None))
        self.fileLabel.setText(_translate("MainWindow", "Enter file name", None))
        self.tabControl.setTabText(self.tabControl.indexOf(self.tabCmd), _translate("MainWindow", "XAFS Scan", None))
        self.label_3.setText(_translate("MainWindow", "Serial Ports:", None))
        self.cbPorts.setProperty("currentText", _translate("MainWindow", "COM1", None))
        self.cbPorts.setItemText(0, _translate("MainWindow", "COM1", None))
        self.btnRescan.setText(_translate("MainWindow", "ReScan", None))
        self.label_4.setText(_translate("MainWindow", "Baud Rates:", None))
        self.cbBaudrate.setProperty("currentText", _translate("MainWindow", "115200", None))
        self.cbBaudrate.setItemText(0, _translate("MainWindow", "1200", None))
        self.cbBaudrate.setItemText(1, _translate("MainWindow", "2400", None))
        self.cbBaudrate.setItemText(2, _translate("MainWindow", "4800", None))
        self.cbBaudrate.setItemText(3, _translate("MainWindow", "9600", None))
        self.cbBaudrate.setItemText(4, _translate("MainWindow", "19200", None))
        self.cbBaudrate.setItemText(5, _translate("MainWindow", "38400", None))
        self.cbBaudrate.setItemText(6, _translate("MainWindow", "57600", None))
        self.cbBaudrate.setItemText(7, _translate("MainWindow", "115200", None))
        self.cbBaudrate.setItemText(8, _translate("MainWindow", "230400", None))
        self.label_5.setText(_translate("MainWindow", "Serial Thread:", None))
        self.btnSerialStart.setText(_translate("MainWindow", "Start", None))
        self.labelOkay.setText(_translate("MainWindow", "TextLabel", None))
        self.pbOkay.setText(_translate("MainWindow", "Push Button", None))
        self.tabControl.setTabText(self.tabControl.indexOf(self.tabSerial), _translate("MainWindow", "Serial Setting", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionClear.setText(_translate("MainWindow", "Clear", None))
        self.actionClear.setToolTip(_translate("MainWindow", "Clear Terminal screen...", None))
        self.actionClear.setShortcut(_translate("MainWindow", "Alt+C", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave.setToolTip(_translate("MainWindow", "Save Terminal text as...", None))
        self.actionSave.setShortcut(_translate("MainWindow", "Alt+S", None))
        self.actionDir.setText(_translate("MainWindow", "Data directory", None))
        self.actionDir.setToolTip(_translate("MainWindow", "Data directory change...", None))
        self.actionDir.setShortcut(_translate("MainWindow", "Ctrl+D", None))
        self.actionExit.setText(_translate("MainWindow", "exit", None))
        self.actionExit.setToolTip(_translate("MainWindow", "Exit the program...", None))
        self.actionExit.setShortcut(_translate("MainWindow", "Alt+X", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionAbout.setToolTip(_translate("MainWindow", "About PySerialTerminal...", None))
        self.actionAbout.setShortcut(_translate("MainWindow", "Alt+A", None))

from pyqtgraph import PlotWidget
